development:
  cloud_name: <%= ENV["CLOUDNAME"] %>
  api_key: <%= ENV["APIKEY"] %>
  api_secret: <%= ENV["APISECRET"] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= ENV["CLOUDNAME"] %>
  api_key: <%= ENV["APIKEY"] %>
  api_secret: <%= ENV["APISECRET"] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: <%= ENV["CLOUDNAME"] %>
  api_key: <%= ENV["APIKEY"] %>
  api_secret: <%= ENV["APISECRET"] %>
  enhance_image_tag: true
  static_file_support: false